[general.github.orgs.gfx-rs]
unmatched-repo-prefix = "repo-only"

[general.github.orgs.rust-lang.repos.cargo]
prefix = "repo-only"

[general.github.orgs.rust-lang.repos.rust]
prefix = "repo-only"

[general.github.orgs.rust-lang.repos.rust-clippy]
prefix = "repo-only"

[general.github.orgs.rust-lang.repos.rustdoc]
prefix = "repo-only"

[general.github.orgs.rust-lang.repos.rustup]
prefix = "repo-only"

[general.github.orgs.ErichDonGubler.repos.moz-webgpu-cts]
prefix = "repo-only"

[general.github.orgs.gpuweb.repos.gpuweb]
prefix = "repo-only"

[general.github.orgs.rust-windowing.repos.glutin]
prefix = "repo-only"

[general.github.orgs.BabylonJS.repos."Babylon.js"]
prefix = "repo-only"

[profiles.wgpu.github.orgs.gfx-rs.repos.wgpu]
prefix = "none"

[profiles.fx-webgpu]

[profiles.gpuweb.github.orgs.gpuweb]
unmatched-repo-prefix = "repo-only"

[profiles.gpuweb.github.orgs.gpuweb.repos.gpuweb]
prefix = "none"
